### ISSUE TITLE
binar files

### ISSUE THREAD

**Issue by AMD-NICK** [danielga/gmsv_serversecure#1]
Please make and upload binar files to repo. Thanks in advance

**Comment by notcake** [comment]
What is a binar file?

**Comment by AMD-NICK** [comment]
I do not know how it named at English but I mean that compilled file
Just I don't know how to compile it by myself and need your help

**Comment by danielga** [comment]
Bad joke tags :x

**Comment by AMD-NICK** [comment]
Oh, my system is Ubuntu Server 12.04

**Comment by danielga** [comment]
New release available for Linux: https://github.com/danielga/gmsv_serversecure/releases

Closed.
