### ISSUE TITLE
Reset serversecure table after maprestart

### ISSUE THREAD

**Issue by AMD-NICK** [danielga/gmsv_serversecure#10]
I don't speak English to describe a problem in details so just do ulx maprestart and you will see empty serversecure table:

![image](https://cloud.githubusercontent.com/assets/9200174/23827185/50a3a25a-06b6-11e7-8b40-5ec0f085a99b.png)

![image](https://cloud.githubusercontent.com/assets/9200174/23827191/638853f2-06b6-11e7-82fe-d8088af8d0a7.png)

**Comment by danielga** [comment]
Does this also happen when you do a "changelevel current_map_name_here"?

**Comment by AMD-NICK** [comment]
+
![image](https://cloud.githubusercontent.com/assets/9200174/24864980/8e31a062-1e0e-11e7-9071-23c98d7ce188.png)

**Comment by AMD-NICK** [comment]
no effect \_ :| _/

**Comment by AMD-NICK** [comment]
![image](https://cloud.githubusercontent.com/assets/9200174/24972072/b7b6cb28-1fc2-11e7-8a51-54ded5a14e10.png)

**Comment by danielga** [comment]
If this one doesn't work, I don't know what else will.

**Comment by AMD-NICK** [comment]
👍 ;)
seems good to me
