### ISSUE TITLE
Showing "base" gamemode in queries

### ISSUE THREAD

**Issue by jackson-c** [danielga/gmsv_serversecure#11]
When I view game info on a friend on my server, it shows gamemode = base. I am using the multithreaded query cache.

**Comment by danielga** [comment]
I'm unable to reproduce this. Have you tried calling serversecure.RefreshInfoCache() to see if it's still the same afterwards?

**Comment by jackson-c** [comment]
That fixed it, thanks. Do I need to run that once on startup or on a timer?

**Comment by danielga** [comment]
With the example file, I've never had this problem. If you still get this problem with the example (or a modified version of), I'd recommend adding a timer to refresh the info cache.
