### ISSUE TITLE
Not post initializing

### ISSUE THREAD

**Issue by jackson-c** [danielga/gmsv_serversecure#12]
I had to make my code like this to fix some errors:

	require("serversecure")
	if serversecure.EnableInfoCache==nil then
		serversecure.PostInitialize()
	end

**Comment by danielga** [comment]
It's specified in the [example](https://github.com/danielga/gmsv_serversecure/blob/master/example.lua) file.

**Comment by jackson-c** [comment]
Ah, ok. I was using an older version of the lua file.
