### ISSUE TITLE
Feature Request: Stop server hangs (infinite loops)

### ISSUE THREAD

**Issue by cannon** [danielga/gmsv_serversecure#14]
I think that server hangs such as LUA infinite loops could be prevented by using a separate thread to periodically check the main thread and kill the process if it stops running (so it can auto reboot).

My idea for implementing this is having a global boolean variable, where the main thread sets it to true in a Tick hook, then the monitor thread runs every 5 seconds or so and if the variable is true, sets it to false, but if the variable is false, kill the process. Could you please try something like this?

**Comment by danielga** [comment]
I think this is beyond the purpose of this module. There are plenty "guard dogs" for Source engine dedicated servers out there.

**Comment by cannon** [comment]
I've never found a program to restart the server when it hangs, though. Srcds guardian (the batch script) and other things only restart the server if it crashes.
