### ISSUE TITLE
Increasing CPU usage by serversecure.EnableThreadedSocket(true)

### ISSUE THREAD

**Issue by AMD-NICK** [danielga/gmsv_serversecure#15]
As soon as I call `serversecure.EnableThreadedSocket(true)` function, server starts use full CPU thread.

I have 3 servers and I see this before I call the function:
![image](https://user-images.githubusercontent.com/9200174/27881620-129722ee-61d2-11e7-86d2-66c899288b7a.png)

And this after:
![image](https://user-images.githubusercontent.com/9200174/27881629-1a576b2e-61d2-11e7-9c42-6d1878eb1d81.png)

It doesn't cause server lagging (I'm not sure) but I think it's may cause server crash
Just type `lua_run serversecure.EnableThreadedSocket(true)` to see this yourself

**Comment by danielga** [comment]
I believe I may have figured out what's wrong. [select](http://man7.org/linux/man-pages/man2/select.2.html) may change the timeval values and I don't reset them after each call to select.
