### ISSUE TITLE
Abusive "Unknown Command" packets

### ISSUE THREAD

**Issue by cannon** [danielga/gmsv_serversecure#19]
Skids are crashing my server by sending mass amounts of invalid console commands. Server console is spammed with `Unknown Command: "foobar"` which I believe is what causes the lag.

A stopgap is to define the command to just ban the calling player. Can this addon be changed to block unknown console commands? Or just a player sending 10000 commands at once. Thanks!

**Comment by danielga** [comment]
I'd recommend looking into overriding concommand.Run (possibly returning true and removing prints when an unknown command is received). I'd rather avoid adding new features to this module for now.
