### ISSUE TITLE
Crash on Startup with New GMod Update (26 February 2018)

### ISSUE THREAD

**Issue by Hazbelll** [danielga/gmsv_serversecure#20]
As the title says, the Server begins starting up before spitting the following out once trying to load the Binary Module:
```
[ERROR] unable to find CNetChan::IsValidFileForTransfer
  1. unknown - [C]:-1
   2. require - [C]:-1
    3. unknown - lua/includes/modules/serversecure.lua:1
     4. require - [C]:-1
      5. unknown - lua/autorun/server/sv_serversecure.lua:1
```
Which immediately after, SRCDS crashes.

**Comment by cannon** [comment]
Same, this addon seems to break with every gmod update. Otherwise great though.

**Comment by cannon** [comment]
Does the new release fix it? Can we get it compiled please?

**Comment by danielga** [comment]
The CI jobs were failing and I wanted to fix that first.

**Comment by danielga** [comment]
The jobs have now completed successfully, builds are up.

**Comment by cannon** [comment]
Can we get a win32?
