### ISSUE TITLE
InfoCache breaks Game Tag

### ISSUE THREAD

**Issue by G-Force007** [danielga/gmsv_serversecure#22]
When I use serversecure.EnableInfoCache(true) it reverts the GAMEMODE name to "base" instead of the actual real GAMEMODE name.

Attached 2 screenshots to show
![hl2_2018-03-04_01-13-32](https://user-images.githubusercontent.com/2627970/36935226-572f631e-1f49-11e8-8c2a-5bca3dadd561.png)
![hl2_2018-03-04_01-13-45](https://user-images.githubusercontent.com/2627970/36935228-59daff7e-1f49-11e8-9fe1-f13165a62b6d.png)

**Comment by G-Force007** [comment]
If EnablePacketValidation is set to false while EnableInfoCache is true, this bug doesn't occur. Seems to be related to both Packet Validation and InfoCache

**Comment by danielga** [comment]
So this happens because by the time the packet builder function calls `GetGameDescription`, that returns "base". The solution is to call `serversecure.RefreshInfoCache` later on, which I am going to add to the pure Lua module.

**Comment by danielga** [comment]
I've pushed a patch for this, CIs will build it in the meantime.

**Comment by danielga** [comment]
Oh and make sure to update the Lua module too.

**Comment by G-Force007** [comment]
It was on base for a bit and then changed over. Thanks, that fixed it.
