### ISSUE TITLE
New gmod update broke it

### ISSUE THREAD

**Issue by Jueyi9ww** [danielga/gmsv_serversecure#23]
hello. the module doesn't work anymore after the new update what just came out for gmod. 

https://gmod.facepunch.com/blog/august-2018-hotfix/
[ERROR] unable to find CNetChan::IsValidFileForTransfer

**Comment by danielga** [comment]
@Jueyi9ww I suppose this happened on Windows?

**Comment by Jueyi9ww** [comment]
@danielga that's correct. still working on linux by the looks of it, just windows it's broken on. would you have time to fix it today?

**Comment by danielga** [comment]
@Jueyi9ww can you try [these builds](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.20) please?

**Comment by Jueyi9ww** [comment]
@danielga works like a charm, thank you very much! <3

**Comment by danielga** [comment]
Awesome!
