### ISSUE TITLE
July 2019 Update

### ISSUE THREAD

**Issue by WdTense** [danielga/gmsv_serversecure#27]
I believe the new update broke parts of this module. I don't have an error on hand but my server doesn't appear on the server browser with this module after the update.

https://steamcommunity.com/games/garrysmod/announcements/detail/1613893608702276302

**Comment by FarukGamer** [comment]
[debug.log](https://github.com/danielga/gmsv_serversecure/files/3351598/debug.log)

I'm not sure if this is helpful, but here are the debug logs.

**Comment by storm37000** [comment]
Can confirm i have the issue too after the update,  My server is just segfault boot looping so that is probably what yours is doing too.

**Comment by VaasKahnGrim** [comment]
aye same issue aswell, happening the moment its loaded. before any of the functions are ever used.(confirmed using print("test #) in various places to find out it was this module causing it to crashloop)

**Comment by jbohack** [comment]
I can confirm as well the server sits at a loop for segfault loops.

**Comment by danielga** [comment]
I believe this is fixed on version [1.5.24](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.24).

**Comment by storm37000** [comment]
yes its fixed now.
