### ISSUE TITLE
This broke on latest gmod update

### ISSUE THREAD

**Issue by haleylovesroses** [danielga/gmsv_serversecure#28]
This seems to cause the legacy server browser to show "base" instead of "Sandbox" as the gamemode when this is installed. I removed it, and the gamemode went back to normal. It also seems to be affecting visibility in the server browser as my server sometimes doesn't show when this is installed.

**Comment by haleylovesroses** [comment]
found the error.   Disabling this corrects the issues. serversecure.EnableInfoCache(true) -- enable A2S_INFO response cache

**Comment by haleylovesroses** [comment]
it seems were getting random segmentation fault crashes even with that disabled. Please let me know once this is fixed.

**Comment by danielga** [comment]
Please try [these builds](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.27-5). I'm not sure if they'll fix Linux issues however.

**Comment by danielga** [comment]
I believe this is related to #36, if the issue persists, please open a new one.
