### ISSUE TITLE
Can't seem to get premake5 to create an sln file for the project

### ISSUE THREAD

**Issue by VaasKahnGrim** [danielga/gmsv_serversecure#29]
So I've tried keeping the premake5 .exe and .lua files in the projects folder and moving it to the root folder. I've even edited the .lua file to point to the garrysmod_common folder(from your repo)

yet despite everything I try it simply doesn't build a sln. I simply get a split second where cmd pops up, but immediatly closes. I can't even get an error from it to know whats wrong with it since it closes immediatly

**Comment by danielga** [comment]
This repo still uses the old project generator, but it should work fine since I made it backwards compatible this time. Have you tried opening a command line in that folder and running `premake5 vsXXXX` to get more output? That way, it should keep it open.

**Comment by VaasKahnGrim** [comment]
well I managed to get the error this time but it doesn't really make much sense to me.

C:\Users\cewei\Downloads\gmsv_serversecure-master (1)\gmsv_serversecure-master\projects>premake5 vs2019
Error: ...aster (1)/gmsv_serversecure-master/projects/premake5.lua:4: invalid escape sequence near '"C:\U'

and below is the lua code for the premake5.lua(I double checked the folderpath for garrysmod_common and it should be exactly as file explorer shows it)

I also tried with the file path for garrysmod_common set to "../dependancies/garrysmod_common" aswell just to see if it worked. but that one simply errors out on line 8 saying I didn't provide a path to garrysmod_common

```
newoption({
	trigger = "gmcommon",
	description = "Sets the path to the garrysmod_common (https://github.com/danielga/garrysmod_common) directory",
	value = "C:\Users\cewei\Downloads\rn_modules\garrysmod_common\garrysmod_common"
})

local gmcommon = _OPTIONS.gmcommon or os.getenv("GARRYSMOD_COMMON")
assert(gmcommon ~= nil, "you didn't provide a path to your garrysmod_common (https://github.com/danielga/garrysmod_common) directory")
include(gmcommon)

CreateWorkspace({name = "serversecure.core", abi_compatible = true})
	CreateProject({serverside = true})
		IncludeSDKCommon()
		IncludeSDKTier0()
		IncludeSDKTier1()
		IncludeSteamAPI()
		IncludeDetouring()
		IncludeScanning()
		files({
			"../source/netfilter/*.cpp",
			"../source/netfilter/*.hpp"
		})
```

**Comment by VaasKahnGrim** [comment]
well I managed to get past the issue with premake5 by manually editing the lua files for it to automatically point to the path.

tho now I'm unsure what to do with the new issue I have. I tried building it on release win32 with no edits made but I get this in my error console for vs https://pastebin.com/s6eV1K13

**Comment by danielga** [comment]
The path error is related to you editing the file directly and improperly. You're supposed to edit environment variables of your terminal/command line. `GARRYSMOD_COMMON` contains the path to your local copy of the `garrysmod_common` repository and `SOURCE_SDK` the path to your local copy of my `sourcesdk-minimal` repository.
Regarding that error, I've made a fix on `garrysmod_common` so make sure to pull the latest changes.
