### ISSUE TITLE
Premake5.lua error - can't create vs2010 project

### ISSUE THREAD

**Issue by uRandomAlex** [danielga/gmsv_serversecure#3]
I'm getting this error when trying to create vs2010 project from premake:
`Error: ...inary/gmsv_serversecure/projects/premake5.lua:22: attempt to call global 'CreateSolution' (a nil value)`

My command-line:
```
set GARRYSMOD_COMMON=path/to/garrysmod_common-master/
set SOURCE_SDK=path/to/sourcesdk-minimal-master/

premake5 --os=windows --platform=x32 vs2010
pause
```

I've tried to do this with --gmcommon=path, but I'm getting the same error.

**Comment by danielga** [comment]
Have you pulled recently? That shouldn't be happening.

**Comment by uRandomAlex** [comment]
I've downloaded everything before making this issue using .ZIP archives, not GIT.

**Comment by danielga** [comment]
Well, your files are out of date because if you look at projects/premake5.lua in this repo it reads
`CreateWorkspace({name = "serversecure", allow_debug = false})`
There's no CreateSolution anywhere.

**Comment by uRandomAlex** [comment]
That's strange. I will redownload them and try again.

**Comment by uRandomAlex** [comment]
Ok, now I'm getting that errors:
```
..\..\..\source\filecheck.cpp(7): fatal error C1083: symbolfinder.hpp: No such file or directory [path\to\gmsv_serversecure\projects\windows\vs2010\gmsv_serversecure.vcxproj]
..\..\..\source\netfilter.cpp(18): fatal error C1083: symbolfinder.hpp: No such file or directory [path\to\gmsv_serversecure\projects\windows\vs2010\gmsv_serversecure.vcxproj]
```

**Comment by danielga** [comment]
That seems like you have a bad garrysmod_common copy or a bad path to it.

**Comment by uRandomAlex** [comment]
Eh... GitHub don't download "folder @ gar4bage" folders contents. I'm downloading them manually now.

**Comment by uRandomAlex** [comment]
It's working! Thanks for help!
