### ISSUE TITLE
Problems with version 1.5.25

### ISSUE THREAD

**Issue by FarukGamer** [danielga/gmsv_serversecure#32]
I experience strange problems using the module.
The operating system is Debian 10 with kernel version 5.3.7

This error appears:
```
L 10/31/2019 - 09:58:43: Lua Error: 
[ERROR] unable to get server factory
  1. unknown - [C]:-1
   2. require - [C]:-1
    3. unknown - lua/includes/modules/serversecure.lua:1
     4. require - [C]:-1
      5. unknown - lua/autorun/server/sv_serversecure.lua:1


L 10/31/2019 - 09:58:43: Lua Error: 
[ERROR] lua/autorun/server/sv_serversecure.lua:1: Module not found!
  1. require - [C]:-1
   2. unknown - lua/autorun/server/sv_serversecure.lua:1
```

**Comment by vega0** [comment]
Same error
https://i.imgur.com/0mowUMB.png

**Comment by danielga** [comment]
What branch of Garry's Mod are you using this on? This currently only works on the default branch.

**Comment by FarukGamer** [comment]
I am on the default branch.

**Comment by danielga** [comment]
Please try [this release](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.26) when it finishes building.

**Comment by FarukGamer** [comment]
It seems the problem has been fixed.

**Comment by danielga** [comment]
I forgot to bump the version so I'll make another release.
