### ISSUE TITLE
Not working under Cent OS 7

### ISSUE THREAD

**Issue by vega0** [danielga/gmsv_serversecure#33]
require "serversecure.core"

> 	[string "*"]:0: Couldn't load module library!
> 	 1: (message = "[string \"*\"]:0: Couldn't load module library!") [addons/gcompute/lua/gcompute/execution/local/gluaexecutioninstance.lua: 178]
> 	 2:  ("serversecure.core", userdata: 0xede5f0c8, "/lib/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/gmod_nsds/garrysmod/lua/bin/gmsv_serversecure.core_linux.dll)", "Couldn't load module library!") [[C]: -1]
> 	 3: (__param1 = "serversecure.core") [[string "*"]: 0]
> 	 4: xpcall (function (message)) [[C]: -1]
> 	 5: Start (self = { GCompute.Execution.GLuaExecutionInstance: 0xedde71e8 }) [addons/gcompute/lua/gcompute/execution/local/gluaexecutioninstance.lua: 173]
> 	 6: CreateExecutionInstance (self = { GCompute.Execution.GLuaExecutionContext: 0xed6090b8 }, code = "require \"serversecure.core\"", sourceId = "@repl_0", instanceOptions = 6, callback = nil) [addons/gcompute/lua/gcompute/execution/executioncontext.lua: 56]
> 	 7: HandleExecutionInstanceCreationRequest0 (self = { GCompute.Execution.RemoteExecutionContextHost: 0xeecd6dc0 }, connection = { GLib.Net.Connection: 0xed6063f0 }, inBuffer = { GLib.Net.Layer1.PinnedNetInBuffer: 0xeed5ecc0 }) [addons/gcompute/lua/gcompute/execution/remote/remoteexecutioncontexthost.lua: 94]
> 	 8: (self = { GCompute.Execution.RemoteExecutionContextHost: 0xeecd6dc0 }, connection = { GLib.Net.Connection: 0xed6063f0 }, inBuffer = { GLib.Net.Layer1.PinnedNetInBuffer: 0xeed5ecc0 }) [addons/gcompute/lua/gcompute/execution/remote/remoteexecutioncontexthost.lua: 78]
> 	 9: xpcall (GLib.Error) [[C]: -1]
> 	10: () [addons/glib/lua/glib/threading/thread.lua: 262]
>

**Comment by danielga** [comment]
Unfortunately, CentOS has this weird policy of having everything super outdated. The issue is that CentOS 7 glibc is too old. Your best course of action will be to compile the module yourself.
