### ISSUE TITLE
1.5.26 causing segfaults for no reason, 1.5.24 was fine.

### ISSUE THREAD

**Issue by storm37000** [danielga/gmsv_serversecure#34]
```
[909220.998353] srcds_linux[14642]: segfault at f7f9c7cc ip 00000000f7ef6858 sp 00000000eacb5180 error 4 in libpthread-2.28.so[f7ef6000+1000]
[909221.001890] Code: 77 28 89 c3 83 ec 0c 52 e8 b5 f8 ff ff 83 c4 10 89 d8 8b 74 24 1c 65 33 35 14 00 00 00 75 1d 83 c4 20 5b 5e 5f c3 8d 74 26 00 <8b> 8e ac ff ff ff f7 d8 bb ff ff ff ff 65 89 01 eb c8 e8 a1 33 00
```

**Comment by storm37000** [comment]
this specific error never happened before i updated it from 1.5.24 to 1.5.26.

**Comment by danielga** [comment]
Those lines don't really tell me anything. How reproducible is this?

**Comment by storm37000** [comment]
its happened about 7 times in the past 24 hours which is when i updated the dll.  Before that ive never seen that error.

**Comment by danielga** [comment]
If you're able to, run your server under GDB, whenever it crashes, it'll freeze it and show you a stacktrace. A debug build of the module is also useful.

**Comment by storm37000** [comment]
Is there a way to have to dump the stacktrace to a file and continue.  This is a pretty busy production server and i cant have any downtime.

**Comment by danielga** [comment]
Please try [these builds](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.27-5). I'm not sure if they'll fix Linux issues however.
