### ISSUE TITLE
1.5.26 Windows | serversecure.EnableThreadedSocket crashes the game

### ISSUE THREAD

**Issue by GitSparTV** [danielga/gmsv_serversecure#35]
serversecure.EnableThreadedSocket(true) crashes the game without any logs. Works fine without setting it to true.
1.5.26. main branch, srcds. GMod 191111

**Comment by danielga** [comment]
Please try [these builds](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.27-5).

**Comment by GitSparTV** [comment]
Still Crashing

**Comment by GitSparTV** [comment]
It crashes just with require("serversecure"), no additional settings

**Comment by danielga** [comment]
It's broken signatures. Currently fixed one but something else is also broken.

**Comment by Heavybob** [comment]
REEEE why you break!

**Comment by danielga** [comment]
Got some [new builds up](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.27-6). I think I finally fixed the issue with these.

**Comment by Heavybob** [comment]
Testing release now, appears all goochie.

**Comment by GitSparTV** [comment]
Works for me

**Comment by danielga** [comment]
Issue fixed with #36.

**Comment by GitSparTV** [comment]
serversecure.EnableThreadedSocket causes client to time out on reconnecting after `changelevel` or hangs server on shutdown

**Comment by danielga** [comment]
`serversecure.EnableThreadedSocket` is deprecated on the latest version. Update the Lua module and open a new issue if this is reproducible on 1.5.28.
