### ISSUE TITLE
[enhancement] Sync gmsv_query with latest gmsv_serversecure tree

### ISSUE THREAD

**Issue by MVoloshin** [danielga/gmsv_serversecure#37]
Hello, I am trying to make a working gmsv_query (https://github.com/DuckyC/gmsv_query) library for linux (it contains about 90% of source code from serversecure, but does not work out-of-box because its based on very outdated version). So I tried to apply post-2016 commits and was able to get module recognized and loaded, but then it fails on recvfrom() in libpthread.so. https://yadi.sk/d/cQa1XrgKoHp8XQ
Could you help me, please? I need this library for testing purposes.

**Comment by MVoloshin** [comment]
According to backtrace failure is caused by recvfrom_detour.
In the console I see something like this:
server startup ...
A2S_INFO from 92.158.127.202 27015
A2S_INFO from 92.158.127.202 27015
A2S_INFO from 92.158.127.202 27015
Segmentation fault.
P.S. I have uploaded my code here: https://yadi.sk/d/cQa1XrgKoHp8XQ

**Comment by danielga** [comment]
I can't update their repo, but you can get the latest code and try to fix it. I fixed the latest crashes with 1.5.28.

**Comment by AjStyles2** [comment]
> I can't update their repo, but you can get the latest code and try to fix it. I fixed the latest crashes with 1.5.28.

Sorry for stupid question, but what part of code i need to merge with yours for make it works?
