### ISSUE TITLE
Secureserver dies on map change. 

### ISSUE THREAD

**Issue by Heavybob** [danielga/gmsv_serversecure#38]
Testing 1.5.27-6 and 1.5.27

Server dies on map change.

**Comment by danielga** [comment]
What platform is this happening on?

**Comment by Heavybob** [comment]
Windows Server 2016,

**Comment by danielga** [comment]
I'm unable to replicate this on Windows 10, with Garry's Mod SRCDS on main branch. Any dumps you can send my way?

**Comment by Heavybob** [comment]
Idk what to tell you, when doing a normal map change the server will halt and will become unresponsive. If you want me to dump something or do some debugging for it, I'm cool with that.

**Comment by danielga** [comment]
Ah, there we go. So it's not a crash. I was able to reproduce the freezing however. Can you try disabling the infocache and see if it still happens please?

**Comment by Heavybob** [comment]
Apologies for not making that clear. 
I'll give that a test later tonight and get back to you. 
Infocache was enabled during the prior tests.

**Comment by danielga** [comment]
I believe [this build](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.28) should fix the issue.

**Comment by G-Force007** [comment]
Looking good so far.

**Comment by danielga** [comment]
I'm considering this fixed.

**Comment by Heavybob** [comment]
Thanks daniel.
