### ISSUE TITLE
1.5.28 lua error

### ISSUE THREAD

**Issue by storm37000** [danielga/gmsv_serversecure#40]
```
[ULib] lua/autorun/server/sv_a2scache.lua:4: attempt to call field 'EnableThreadedSocket' (a nil value)
  1. fn - lua/autorun/server/sv_a2scache.lua:4
   2. unknown - lua/ulib/shared/hook.lua:109
```

**Comment by danielga** [comment]
You didn't update the Lua module.

**Comment by storm37000** [comment]
the ThreadedSocket is basically the only reason i use this, ive never had any issues with it.  Without it my servers ping in the server list is almost 2x as high as it should be.  Without this feature my server would likely have much reduced traffic.

**Comment by danielga** [comment]
I removed the toggle because it was just making the code more complicated. It's always on now. The Lua module just useless, backwards compatible functions.
