### ISSUE TITLE
1.5.29 segfaults

### ISSUE THREAD

**Issue by storm37000** [danielga/gmsv_serversecure#43]
```
 srcds_linux[22259]: segfault at 2aa3d7cc ip 000000002a996858 sp 00000000075161e0 error 4 in libpthread-2.28.so[2a996000+1000]
[1322789.186062] Code: 77 28 89 c3 83 ec 0c 52 e8 b5 f8 ff ff 83 c4 10 89 d8 8b 74 24 1c 65 33 35 14 00 00 00 75 1d 83 c4 20 5b 5e 5f c3 8d 74 26 00 <8b> 8e ac ff ff ff f7 d8 bb ff ff ff ff 65 89 01 eb c8 e8 a1 33 00
```
I do have a core dump.  I will have to send you the link to it somewhere private.

**Comment by storm37000** [comment]
Also the amount of players joining my server dropped massively with the new version vs 1.5.24 which is what i have to go back to as its the latest working version for me.  This was not due to the crashes, it was as soon as i upgraded it before anything crashed.

**Comment by storm37000** [comment]
still happens, it is very infrequent, but when it does, it is sometimes a few times in a row a few minutes after server starts back up each time.  When i was testing with gmod dll modules, the libpthread error would happen when your thread closed without joining with main thread.  This close can be a crash or legit close without a join.  So if your module has no way of closing threads unexpectedly without joining then the thread must be crashing.  This may even be caused by an outside source like a player trying to ddos sending a bad query packet or something.

**Comment by danielga** [comment]
The thread I create is being joined in the main thread, at module unloading, so I don't know how that part could be causing issues.

**Comment by storm37000** [comment]
it means the thread is running into an unhandled exception somewhere and crashing, thus not being joined due to the unexpected crash.

**Comment by Brouskat** [comment]
I use it on two very populated servers and I never had a crash about this issue.
Did you tried on a vanilla server ?

**Comment by storm37000** [comment]
vanilla? this is for linux running on debian 10, the error stops altogether if i downgrade to the last functioning stable version (1.5.24)

**Comment by Brouskat** [comment]
When I mean vanilla, I mean a server with no addons, nothing configured.

Did you tried on Deb 9 ? (cause we are on 9)

**Comment by storm37000** [comment]
no, i have 10 which is the current stable version, im not ever going to downgrade as that would be too much of a pain/downtime

**Comment by danielga** [comment]
What's your list of modules? Any custom made ones/available source code?

**Comment by storm37000** [comment]
just this one, mysqloo, and mine(antifreeze, it is on github)

**Comment by danielga** [comment]
Closing issues related to old versions, new version is [1.5.32](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.32).
