### ISSUE TITLE
"Couldn't load module library"

### ISSUE THREAD

**Issue by tuitcattail** [danielga/gmsv_serversecure#45]
on latest debian 10 with your example file, it doesn't work

`[ERROR] lua/autorun/server/serversecure.lua:1: Couldn't load module library!
  1. require - [C]:-1
   2. unknown - lua/autorun/server/serversecure.lua:1`

**Comment by danielga** [comment]
If you placed the module in the correct place, what I recommend is using [gmod_require](https://github.com/danielga/gmod_require)  to get a proper error explaining what's happening there.

**Comment by tuitcattail** [comment]
/garrysmod/lua/includes/modules/serversecure.lua (the includes file)
/garrysmod/lua/autorun/server/serversecure.lua (the example file)
/garrysmod/lua/bin/gmsv_serversecure.core_linux.dll (latest release) 

i tested changing the require in both files to just serversecure instead of serversecure.core and that got rid of the error however the server boot loops on PREP OK

**Comment by danielga** [comment]
Use gmod_require and don't change those requires, you're creating a require loop.

**Comment by tuitcattail** [comment]
i have installed the require dll and it's include file and yet no more info about that "Couldn't load module library" shows. am i doing something wrong?

could it be an issue with debian 10's binarys? i might be missing something? i previously had this running perfectly on windows.

**Comment by danielga** [comment]
You need to `require("require")` somewhere, like at the top of `/garrysmod/lua/autorun/server/serversecure.lua`, for example.

**Comment by tuitcattail** [comment]
```
[ERROR] lua/includes/modules/require.lua:153: error loading module 'serversecure.core' from file 'gmsv_serversecure.core_linux.dll':
	bin/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by garrysmod/lua/bin/gmsv_serversecure.core_linux.dll)
  1. error - [C]:-1
   2. searcher - lua/includes/modules/require.lua:58
    3. require - lua/includes/modules/require.lua:140
     4. loader - includes/modules/serversecure.lua:1
      5. require - lua/includes/modules/require.lua:153
       6. unknown - lua/autorun/server/secureserver.lua:2
```

however i do have it installed?

```
# strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
```

**Comment by tuitcattail** [comment]
just tested with a fresh ubuntu 18.04 LTS version too and i get exactly the same error as above. 

i installed `apt-get install lib32stdc++6` from https://developer.valvesoftware.com/wiki/SteamCMD#32-bit_libraries_on_64-bit_Linux_systems
