### ISSUE TITLE
Travis CI script?

### ISSUE THREAD

**Issue by VaasKahnGrim** [danielga/gmsv_serversecure#46]
Could you possibly add a Travis CI script for build automation by chance? Would make things quite easy

**Comment by danielga** [comment]
There's a template [here](https://github.com/danielga/garrysmod_common/blob/master/build/.travis.yml.template). You just need to modify some variables and remove a few entries from `deploy:files`. Since I'm not going to be using Travis CI, I won't be adding it to this repo.
