### ISSUE TITLE
Potential issues with new A2S_INFO changes by valve?

### ISSUE THREAD

**Issue by sobabake** [danielga/gmsv_serversecure#54]
These new changes to the protocol have rolled out in the Steam Client Beta already and people have reported problems with seeing some servers. Would this module need an update to be compatible with these new changes?

https://steamcommunity.com/discussions/forum/14/2989789048633291344

**Comment by danielga** [comment]
From what I've read on that thread, the changes are backwards compatible and this module shouldn't need an update to be so. At most, I'd update it to be as restrictive as these changes are.
