### ISSUE TITLE
Steam beta update breaks length checking for A2S_INFO and others

### ISSUE THREAD

**Issue by deadmonstor** [danielga/gmsv_serversecure#55]
The new steam client update pads the length to exactly 1200 or more in length meaning it fails on more than one check. 

Length checked [here](https://github.com/danielga/gmsv_serversecure/blob/master/source/netfilter/core.cpp#L562)
Before update: https://i.imgur.com/MTH6OJQ.png
After update: https://i.imgur.com/W76LKPN.png

[This ](https://github.com/danielga/gmsv_serversecure/blob/master/source/netfilter/core.cpp#L581)is the main function that I was looking into and it fails to even send back request for A2S_INFO because it reports back that it is an invalid packet and should be dropped. 

Length check here: https://github.com/danielga/gmsv_serversecure/blob/master/source/netfilter/core.cpp#L441

**Comment by danielga** [comment]
Thanks for the heads up. I think I'll just check for either 25 or 1200 bytes of length, don't think they'd just change it randomly or later in time.

**Comment by deadmonstor** [comment]
Gone ahead and looked into it and can confirm that PR will fix the issue.

**Comment by danielga** [comment]
Unfortunately, I had already tested a fix with some other changes, #57 supercedes #56.
