### ISSUE TITLE
1.5.31 Segmentation fault

### ISSUE THREAD

**Issue by FarukGamer** [danielga/gmsv_serversecure#58]
### **System Information:**
**OS: Linux Mint 20 "Ulyana"**
**Kernel: 5.4.0-56-generic**

### **Server Information:**
**No addons, no workshop, only the scripts from this GitHub repo.**

### **Console output:**
![serversecure_segfault](https://user-images.githubusercontent.com/12494967/101297309-a26f9100-3828-11eb-8cbd-a31319ab9621.PNG)

### **Debug log:**

```
----------------------------------------------
CRASH: Mo 7. Dez 01:00:03 CET 2020
Start Line: ./srcds_linux -debug -ip 127.0.0.1 -game garrysmod +map gm_construct
End of Source crash report
----------------------------------------------
```

### **Description:**

Well what can I say... This release and the previous versions (https://github.com/danielga/gmsv_serversecure/issues/43 , https://github.com/danielga/gmsv_serversecure/issues/53 ) fail to start the server. Besides, in my case the server doesn't even spit out a real message.

I noticed that the dll file size has changed, normally it should be around 1.9 MB, **The only working version is 1.5.29!**
![grafik](https://user-images.githubusercontent.com/12494967/101297453-5ffa8400-3829-11eb-8d28-7a15bdb69164.png)

**Comment by danielga** [comment]
> I noticed that the dll file size has changed, normally it should be around 1.9 MB
The reason for this is the symbol stripping.

**Comment by danielga** [comment]
> The only working version is 1.5.29!

I've got an issue open saying that version also crashes.

**Comment by FarukGamer** [comment]
Well then, that explains why it is so small size, anyways thank your for the reply.

**Comment by danielga** [comment]
Please try this [new version](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.32).

**Comment by FarukGamer** [comment]
So far it works, I will report if something comes between

```
xxx@virtual-machine:~/Schreibtisch/server_1$ ./srcds_run -debug -ip 127.0.0.1 +map gm_construct
Auto detecting CPU
Using default binary: ./srcds_linux
Enabling debug mode
Server will auto-restart if there is a crash.
Couldn't load shader dll: game_shader_generic_garrysmod_srv.soConVarRef mat_dxlevel doesn't point to an existing ConVar
Game_srv.so loaded for "Garry's Mod"
Setting breakpad minidump AppID = 4000
Initializing Steam libraries for Workshop..
[S_API] SteamAPI_Init(): Loaded 'steamclient.so' OK.
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
CAppInfoCacheReadFromDiskThread took 1 milliseconds to initialize
[S_API FAIL] Tried to access Steam interface SteamUser020 before SteamAPI_Init succeeded.
WS: No +host_workshop_collection or it is invalid!
Adding Filesystem Addon '/home/sunas/Schreibtisch/server_1/garrysmod/addons/serversecure'
Could not find steamerrorreporter binary. Any minidumps will be uploaded in-processUnknown command "cl_cmdrate"
Unknown command "cl_updaterate"
Unknown command "rate"
Network: IP 127.0.0.1, mode MP, dedicated Yes, ports 27015 SV / 27005 CL
Error loading cfg/trusted_keys_base.txt
Error loading cfg/pure_server_minimal.txt
PREP OK
[ServerSecure] serversecure.EnableThreadedSocket is deprecated!
ConVarRef room_type doesn't point to an existing ConVar
Executing dedicated server config file server.cfg
Using map cycle file cfg/mapcycle.txt.
Initializing Steam libraries for secure Internet server
[S_API] SteamAPI_Init(): Loaded 'steamclient.so' OK.
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
CAppInfoCacheReadFromDiskThread took 2 milliseconds to initialize
No account token specified; logging into anonymous game server account.  (Use sv_setsteamaccount to login to a persistent account.)
Connection to Steam servers successful.
   Public IP is xxx.xxx.xxx.xxx.
Assigned anonymous gameserver Steam ID [A-1:14550xxxx(16080)].
VAC secure mode is activated.
```

**Comment by storm37000** [comment]
I decided to try 1.5.32, and after a few days it still seems to have a segfault issue that is very rare but seems to occur in "clumps"
```
[3939330.887787] srcds_linux[21376]: segfault at 2aa917cc ip 000000002a9ea858 sp 00000000043e91f0 error 4 in libpthread-2.28.so[2a9ea000+1000]
[3939330.889321] Code: 77 28 89 c3 83 ec 0c 52 e8 b5 f8 ff ff 83 c4 10 89 d8 8b 74 24 1c 65 33 35 14 00 00 00 75 1d 83 c4 20 5b 5e 5f c3 8d 74 26 00 <8b> 8e ac ff ff ff f7 d8 bb ff ff ff ff 65 89 01 eb c8 e8 a1 33 00
[3950056.567233] srcds_linux[24683]: segfault at 2aa167cc ip 000000002a96f858 sp 00000000043911f0 error 4 in libpthread-2.28.so[2a96f000+1000]
[3950056.568878] Code: 77 28 89 c3 83 ec 0c 52 e8 b5 f8 ff ff 83 c4 10 89 d8 8b 74 24 1c 65 33 35 14 00 00 00 75 1d 83 c4 20 5b 5e 5f c3 8d 74 26 00 <8b> 8e ac ff ff ff f7 d8 bb ff ff ff ff 65 89 01 eb c8 e8 a1 33 00
```

**Comment by danielga** [comment]
@storm37000 please open a new issue and post a stacktrace or dump file, that block of text doesn't contain useful information for me. Include the branch name and architecture of the Garry's Mod dedicated server executable you're using, as well as Linux distro and architecture.

**Comment by storm37000** [comment]
I emailed you a core dump a year ago.  I am using the default branch of the game server on Debian 10.

**Comment by danielga** [comment]
> I emailed you a core dump a year ago.

I'm not supporting older versions. That dump is outdated and I don't even have it anymore.

**Comment by storm37000** [comment]
The error seems to be happening at the same opcode every time.
