### ISSUE TITLE
No 64Bit builds

### ISSUE THREAD

**Issue by TomDotBat** [danielga/gmsv_serversecure#59]
It'd be nice to have a 64bit version of this, as the 64bit version of SRCDS will hopefully be on the main branch soon.

**Comment by bludotbat** [comment]
Any luck? I was going to make a way to do it with gitlab actions

**Comment by danielga** [comment]
I don't have any intentions of adding "official" x86-64 support now or in the near future. Doesn't seem likely the branch will be released any time soon.
