### ISSUE TITLE
New srcds update today broke the module

### ISSUE THREAD

**Issue by storm37000** [danielga/gmsv_serversecure#60]
New srcds update today causes all versions of this module to have a segfault as soon as its initialized.

**Comment by robotboy655** [comment]
https://github.com/danielga/gmsv_serversecure/blob/136810ec5f408c05bbe878eb5b94cff0cb97189c/source/netfilter/core.cpp#L237

This var has been changed, it is now an unsigned long long, not an std::string.

**Comment by danielga** [comment]
Should be fixed by [this release](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.33) (currently building).

**Comment by danielga** [comment]
Closing the issue as this should be fixed.
