### ISSUE TITLE
New EDF flags are missing

### ISSUE THREAD

**Issue by wow0000** [danielga/gmsv_serversecure#63]
Hello,
The following flags are missing from the cache implementation:
* gmc: 
* loc:
* ver:

The implementation can be found here https://github.com/danielga/gmsv_serversecure/blob/master/source/netfilter/core.cpp#L234
Here is an example of the raw Sandbox EDF
` gm:sandbox gmc:other loc:fr ver:210330`

Thank you and have a nice day

**Comment by danielga** [comment]
I've got a [release coming up here](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.34) with these additions.

**Comment by ZZ-RICKI** [comment]
Thanks for the update, just applied the new release to our servers but it still looks like this:
![outdated-noflag](https://user-images.githubusercontent.com/67167240/113468918-98157a80-9449-11eb-86f4-d34f04bc919a.PNG)

If I launch the server without gmsv_serversecure.core_win32.dll in place it looks like how it should be:
![no gmsv_serversecure](https://user-images.githubusercontent.com/67167240/113468929-b11e2b80-9449-11eb-8c5b-6ae186f344f3.PNG)

Hope you figure it out soon, thanks alot for your work^^

**Comment by TomDotBat** [comment]
> Thanks for the update, just applied the new release to our servers but it still looks like this:
> ![outdated-noflag](https://user-images.githubusercontent.com/67167240/113468918-98157a80-9449-11eb-86f4-d34f04bc919a.PNG)
> 
> If I launch the server without gmsv_serversecure.core_win32.dll in place it looks like how it should be:
> ![no gmsv_serversecure](https://user-images.githubusercontent.com/67167240/113468929-b11e2b80-9449-11eb-8c5b-6ae186f344f3.PNG)
> 
> Hope you figure it out soon, thanks alot for your work^^

I've got the same results with the linux version.

**Comment by danielga** [comment]
Yeah, I just noticed my mistake. I clear the server tags dictionary when a full cache rebuild happens but when that happens, the game version isn't set again. Currently fixing this.

**Comment by danielga** [comment]
[New version coming out here.](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.35)

**Comment by TomDotBat** [comment]
Yep it works now

**Comment by ZZ-RICKI** [comment]
!cheers and have some cookies, all seems to be fixed now^^
