### ISSUE TITLE
sv_location and sv_visiblemaxplayers not reported by A2S_INFO after map change

### ISSUE THREAD

**Issue by chuteuk** [danielga/gmsv_serversecure#69]
Steps to reproduce:

> 1. Enable the AS2_INFO cache with serversecure.EnableInfoCache(true)
> 2. Set sv_location and sv_visiblemaxplayers to something in the command line or server.cfg
> 3. AS2_INFO queries report correct values when server first starts
> 4. Change map with changelevel and any AS2_INFO queries no longer report sv_location or sv_visiblemaxplayers 

Either icvar is a nullpointer during Initialize after a map changes or the cvars themselves are not available at this stage because of a different load order. Possible fix by initliaizing these variables each time the info cache is built instead? Strange, tested several times but let me know if you need any more help debugging this.

Thanks :)

**Comment by danielga** [comment]
As a temporary fix, you can call `serversecure.RefreshInfoCache()` to refresh the "static" info cache, updating location and visible max players.

**Comment by chuteuk** [comment]
Thanks for the reply, I did try this already and had it running in the Initialize hook but it doesn't seem to work unfortunately

**Comment by danielga** [comment]
Can you try [this release](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.36-rc3)? It seems modules don't fully unload on changelevels and as such, detour objects were being reused. Since serversecure destroyed detours on "unload", the next load would have a broken detour object, failing to initialize successfully. This silent fail was also fixed, if it happens again, it should error.

**Comment by chuteuk** [comment]
Thanks for looking into this, been trying the **1.5.36-rc3** release now and the problem is still occurring unfortunately. I've changed levels a few times I can't seem to find any errors from it in console either. Is there something in particular to be on the lookout for?

**Comment by danielga** [comment]
I can't reproduce the issue with that build. What OS and Garry's Mod branch are you running the module on?

**Comment by chuteuk** [comment]
I am running the Windows 32bit version of the module and the server is using the default Garry's Mod branch. Tried a few more times this morning and still no luck finding any errors at the moment. Let me know if there's anything else I can do to help find the issue here. Thanks!

**Comment by danielga** [comment]
Was testing on Linux but that is working fine. Managed to reproduced the issue on Windows and [issued a fix on version 1.5.36-rc4](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.36-rc4).

**Comment by chuteuk** [comment]
Hi, thanks. Just tested this a few times now and both sv_location and sv_visiblemaxplayers seem to be updating correctly on the **1.5.36-rc4** release. Thank you!
