### ISSUE TITLE
error `failed to load required CSteamGameServerAPIContext interface` on startup

### ISSUE THREAD

**Issue by fruitwasp** [danielga/gmsv_serversecure#7]
```
[ERROR] failed to load required CSteamGameServerAPIContext interface
  1. unknown - [C]:-1
   2. require - [C]:-1
    3. v - lua/autorun/server/serversecure.lua:2
     4. unknown - lua/includes/modules/hook.lua:84
```

downloaded the latest release from the releases tab, which is 1.3.9 at the time of writing
configs like the [example file](https://github.com/danielga/gmsv_serversecure/blob/master/example.lua)
running on ubuntu 14.04 lts

**Comment by AMD-NICK** [comment]
+
![image](https://cloud.githubusercontent.com/assets/9200174/21595093/c23954b4-d132-11e6-84b3-a12a50698e4f.png)

**Comment by AMD-NICK** [comment]
UPD. No one error in v1.3.8. Only with 1.3.9
