### ISSUE TITLE
64bit?

### ISSUE THREAD

**Issue by Preckster** [danielga/gmsv_serversecure#70]
Please? Pretty please? :)

**Comment by danielga** [comment]
Nothing has changed since January or the year 2020 https://github.com/danielga/gmsv_serversecure/issues/59

**Comment by Preckster** [comment]
People have started using the 64-bit branch, mainly the big nut script servers that can fill an entire game mode by themselves. Thus making server secure useless for them, us smaller communities, however, trying to improve performance, etc, by going 64 bit serverside are taking punishment without it. Please do consider it.

**Comment by danielga** [comment]
I'll have to rewrite the CI build system for that and I can't promise any timeline for it.

**Comment by brandonsturgeon** [comment]
Is it possible for us to build it ourselves?

**Comment by danielga** [comment]
Yes, it is. You'll need to change `garrysmod_common` to the `x86-64-support-sourcesdk` branch, open gmsv_serversecure's `premake5.lua` and change `PROJECT_GENERATOR_VERSION = 2` to `PROJECT_GENERATOR_VERSION = 3`, generate the project files and then build.

**Comment by brandonsturgeon** [comment]
Nice!
I also had to set `config=releasewithsymbols_x86_64` in the Makefile, but it built successfully. I'll get to testing it.

**Comment by Jindego** [comment]
> Nice! I also had to set `config=releasewithsymbols_x86_64` in the Makefile, but it built successfully. I'll get to testing it.

did you get it working?

**Comment by brandonsturgeon** [comment]
Ah, my bad, forgot to update. I was not, unfortunately.
I was able to get it to build, but was never able to successfully `require` it.

But I'm really not a cpp guy - the entire landscape is foreign to me, so I reckon someone with even a little experience might fare better.
