### ISSUE TITLE
x64 binary?

### ISSUE THREAD

**Issue by jellyton69** [danielga/gmsv_serversecure#75]
Hello there, I was wondering if you'd be willing to compile this module to be used on the x64 branch?

**Comment by Jindego** [comment]
64 bit linux would be great :)

**Comment by danielga** [comment]
As I mentioned on #70 and #59, there's no official support for that branch. If you're feeling brave, you can follow the [instructions here](https://github.com/danielga/gmsv_serversecure/issues/70#issuecomment-914529144) to compile the module yourself for x86-64.
