### ISSUE TITLE
Base Gamemode

### ISSUE THREAD

**Issue by Slipsoff** [danielga/gmsv_serversecure#77]
Sorry i missed the lua fix file
I would like to see a Garrysmod x86-64 compatible seems broken.

**Comment by Slipsoff** [comment]
Ok I get it . But after review of my finding the base game still shows in master browser but it's fine in legacy. Very odd.

**Comment by danielga** [comment]
I've tried both the Steam server browser/Garry's Mod legacy server browser and Garry's Mod new server browser. They all worked fine.
