### ISSUE TITLE
[1.4.0] failed to load required CSteamGameServerAPIContext interface

### ISSUE THREAD

**Issue by AMD-NICK** [danielga/gmsv_serversecure#8]
On startup
![image](https://cloud.githubusercontent.com/assets/9200174/21742390/9bd22b44-d4f6-11e6-9e0f-43b588a2954a.png)

On
```lua
lua_run require("serversecure")
```
after server loading
![image](https://cloud.githubusercontent.com/assets/9200174/21742385/8ad9840e-d4f6-11e6-86f0-5ccc5ba5ae1b.png)

![image](https://cloud.githubusercontent.com/assets/9200174/21742401/de626fd2-d4f6-11e6-956d-fc3a910c8525.png)

Previous issue
https://github.com/danielga/gmsv_serversecure/issues/7

Ubuntu 16.04.1

**Comment by danielga** [comment]
Unable to replicate locally. Make sure you remove the old files, shutdown the server, replace the files and restart.

**Comment by fruitwasp** [comment]
Still happens on my instance too. Running `lua_run require("serversecure")` after the server has fully initialized does make `lua_run PrintTable(serversecure)` return the table though.

**Comment by danielga** [comment]
The example script uses the Initialize hook on purpose, you can't require the module before the server is properly initialized.

**Comment by fruitwasp** [comment]
Using the example script. I meant to say that requiring serversecure after the gameserver steamId is assigned, etc. does not produce the error.

**Comment by fruitwasp** [comment]
confirmed to work. Thanks.
