### ISSUE TITLE
SetThreadDescription could not be located in the DLL

### ISSUE THREAD

**Issue by FarikLoL** [danielga/gmsv_serversecure#80]
![image](https://user-images.githubusercontent.com/46515364/149994878-cd923911-dd5f-4c08-b1a7-3858f7c0aee4.png)

**Comment by danielga** [comment]
What's your Windows 10 version number (press `[WINDOWS KEY] + R` and type `winver` in the input box)? `SetThreadDescription` is only available since Windows Server 2016 and Windows 10 version 1607 (10.0.14393).

**Comment by danielga** [comment]
Actually, those versions have special requirements to use `SetThreadDescription`, the minimum version of Windows 10 for the module is actually a bit higher.

**Comment by FarikLoL** [comment]
![image](https://user-images.githubusercontent.com/46515364/149998167-43e9c320-80bf-4d70-bd32-ac9c149c5daf.png)

**Comment by danielga** [comment]
Yeah, you're like at the version limit but it still requires some changes on the module code.

**Comment by FarikLoL** [comment]
this bug appeared in the latest version of the module
there was no error in 1.5.37-rc3

**Comment by danielga** [comment]
Can you try [this build](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.40-rc1) please? It should include a fix for Windows Server 2016 version 1607.

**Comment by FarikLoL** [comment]
server starts without error


what does this line mean? [ServerSecure] serversecure.EnableThreadedSocket is deprecated!

**Comment by danielga** [comment]
It's a warning for you to stop calling that function, because it doesn't do anything anymore.

**Comment by vektoh** [comment]
> ![image](https://user-images.githubusercontent.com/46515364/149994878-cd923911-dd5f-4c08-b1a7-3858f7c0aee4.png)

hi, i got this error when i opened efootball 24 from the folder
any ideas how i can fix this
