### ISSUE TITLE
Example on how to use serversecure.AddBlacklistIP?

### ISSUE THREAD

**Issue by FarikLoL** [danielga/gmsv_serversecure#84]
hi, can you give an example how to use serversecure.AddBlacklistIP(ip_in_integer_format)
I just don't understand how

**Comment by danielga** [comment]
`serversecure.AddBlacklistIP` receives a number representing the IPv4 address you want to blacklist. There's a helper function called `serversecure.StringToIP` that translates a "human-readable" IPv4 address (123.123.123.123) to that number.

**Comment by FarikLoL** [comment]
Thanks
