### ISSUE TITLE
Cannot Build

### ISSUE THREAD

**Issue by LastPlayerTR** [danielga/gmsv_serversecure#86]
![image](https://user-images.githubusercontent.com/73468364/162221645-77a6dd90-0688-427b-960c-862742f786d0.png)
root@ubuntu:~/svsecure/gmsv_serversecure# ./premake5 vs2019 --gmcommon /root/svsecure/garrysmod_common
Error: /root/svsecure/gmsv_serversecure/premake5.lua:13: attempt to call a nil value (global 'CreateWorkspace')

**Comment by danielga** [comment]
Seems like you have a broken `garrysmod_common` copy. Try deleting it and cloning it again with `git clone --recursive https://github.com/danielga/garrysmod_common.git`.

**Comment by LastPlayerTR** [comment]
![image](https://user-images.githubusercontent.com/73468364/162224484-7e48e4ca-ac27-4d8a-b3cb-8931780deb59.png)
Nothing changed.
I can compile garrysmod_common but cannot compile gmsv_serversecure
![image](https://user-images.githubusercontent.com/73468364/162224723-54efbbbe-c7ae-400e-a057-2173cd7416f1.png)

**Comment by LastPlayerTR** [comment]
I set env variable and it solved!
Thanks

**Comment by danielga** [comment]
I just noticed what the problem was. You forgot the `=` after `--gmcommon` (as in, `--gmcommon=/root/svsecure/...`). It's an unfortunate premake annoyance.
