### ISSUE TITLE
Server crash on shutdown

### ISSUE THREAD

**Issue by Dr4iv3rNope** [danielga/gmsv_serversecure#88]
Server crashing when shutting down.

Steps reproduce:
1. Start server.
2. Type "exit".
3. Get a segmentation fault.

I found myself that if you remove [CBaseServerProxy](https://github.com/danielga/gmsv_serversecure/blob/a2d53d94e09bc953fab1db479ae5826e031ada87/source/netfilter/core.cpp#L1028-L1144), then problem will disappear.

**Comment by danielga** [comment]
What Garry's Mod branch and architecture is this happening on?

**Comment by Dr4iv3rNope** [comment]
Ubuntu 20.04 LTS

```
] version
Protocol version 24
Exe version 2021.12.15 (garrysmod)
Exe build: 18:19:41 Mar 10 2022 (8524) (4000)
GMod version 2022.03.17, branch: unknown
Linux 32bit Dedicated Server
```

**Comment by danielga** [comment]
I confirmed the bug and I think I fixed it (on [garrysmod_common](https://github.com/danielga/garrysmod_common)). Can you try [these builds](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.40-rc2)?

**Comment by Dr4iv3rNope** [comment]
Yes, i think it's fixed. Server is not crashing anymore.
