### ISSUE TITLE
steam auth packet (k) abused for ddos attack

### ISSUE THREAD

**Issue by klen-list** [danielga/gmsv_serversecure#89]
Many sandbox servers were attacked using an invalid steam authorization packet size without sending a handshake initialization packet:
![изображение](https://user-images.githubusercontent.com/49125075/167679461-1dd03609-5668-4bc9-9dbd-dc1234b534cc.png)
![изображение](https://user-images.githubusercontent.com/49125075/167678390-fb8993e1-f8f5-4790-a323-3dc53e036928.png)
Tested without attack, here is valid steam auth size:
![изображение](https://user-images.githubusercontent.com/49125075/167678713-6fbdc91b-a632-40c3-8a42-11f51fca33bb.png)

**Comment by danielga** [comment]
I've got a possible solution on [this release candidate](https://github.com/danielga/gmsv_serversecure/releases/tag/1.5.41-rc1). It should validate most of the packet data before allowing it through. I've tested it against a legit Windows Garry's Mod client so it should work for legit clients, don't have a way to test against attackers though.
