### ISSUE TITLE
Problems with premake5

### ISSUE THREAD

**Issue by nicefps** [danielga/gmsv_serversecure#90]
![image](https://user-images.githubusercontent.com/60658899/171996107-c8e0c90a-9743-45b7-83a3-d4db05e2050a.png)
![image](https://user-images.githubusercontent.com/60658899/171996115-09d69ddd-819a-4bed-a72e-274aeed5f0df.png)
![image](https://user-images.githubusercontent.com/60658899/171996118-552a579a-b252-4ada-8cfe-5e542262ac8b.png)
![image](https://user-images.githubusercontent.com/60658899/171996127-1994e041-caa2-43a6-80c1-1c8d4411228e.png)

**Comment by danielga** [comment]
`garrysmod_common` can't be found automatically, without assistance. You need to pass the path through the command (`premake5 --gmcommon="/home/ubuntu/garrysmod_common"`) or through an environment variable (`export GARRYSMOD_COMMON="/home/ubuntu/garrysmod_common"`).
