### ISSUE TITLE
premake5 problem (again, sorry)

### ISSUE THREAD

**Issue by SpawnCodegmd** [danielga/gmsv_serversecure#91]
im sorry for being a bit dump, but i haven't still solve one problem
![image](https://user-images.githubusercontent.com/60658899/172033351-2f53b9ea-e7c5-4f32-8020-1a4f0e0d5e36.png)

**Comment by nicefps** [comment]
okay, fixed that after some time
now i have another problem
![image](https://user-images.githubusercontent.com/60658899/172039812-942ad0a5-caeb-48fd-81fa-0af559ad10fd.png)

**Comment by danielga** [comment]
You need to clone `garrysmod_common` with all of its Git submodules. The easiest way is to delete your current copy of it and retry with `git clone --recursive https://github.com/danielga/garrysmod_common.git`.
