### ISSUE TITLE
premake5 problem

### ISSUE THREAD

**Issue by FarikLoL** [danielga/gmsv_serversecure#94]
.\premake5.exe gmake
Selected version 2 of the project generator
Error: ...garrysmod_common/premake/generator.lua:299: The only supported compilation platforms for this project (gmsv_serversecure.core) on Windows are Visual Studio 2015, 2017, 2019 and 2022.

**Comment by danielga** [comment]
Makefiles are not supported by garrysmod_common on Windows.

**Comment by FarikLoL** [comment]
![image](https://user-images.githubusercontent.com/46515364/193398436-4512bee7-03de-4e47-bc96-752d84ca3fc3.png)
