### ISSUE TITLE
Crash when trying to load a personally assembled module on a Win64 dedicated server.

### ISSUE THREAD

**Issue by unnamed24** [danielga/gmsv_serversecure#95]
In general, the subject, I replaced the line "PROJECT_GENERATOR_VERSION = 2" in premake5.lua with "PROJECT_GENERATOR_VERSION = 3" and compiled using Visual Studio 2022 with the x64 bit version, there were no compilation errors, however, when trying to load the module on the server via "require ( "serversecure" )", the server crashes.
In the "crashes" folder, a stack trace file was generated with the following content:
```
Executable: *secret*\srcds_win64.exe

-Lua Stack Traces-
==================
  Client
    Lua Interface = NULL

  Server
    0. (null) - [C]:-1
      1. require - [C]:-1
        2. (null) - addons/*secret*/lua/includes/modules/serversecure.lua:1
          3. require - [C]:-1
            4. (null) - addons/*secret*/lua/autorun/server/*secret*.lua:1

  MenuSystem
    Lua Interface = NULL

-Console Buffer-
================
7(5.346148):  PREP OK
6(5.343142):  Error loading cfg/pure_server_minimal.txt
5(5.342643):  Error loading cfg/trusted_keys_base.txt
4(0.633639):  Network: IP ***.***.***.***, mode MP, dedicated Yes, ports 27015 SV / 27005 CL
3(0.268564):  Adding Filesystem Addon '*secret*\garrysmod\addons\*secret*'
2(0.204296):  WS: No +host_workshop_collection or it is invalid!
1(0.168178):  Initializing Steam libraries for Workshop..
```
And also a mini-dump, I attached it to the message. (Packed it in ZIP due to GitHub restrictions.)
[unnamed.zip](https://github.com/danielga/gmsv_serversecure/files/10571604/unnamed.zip)
The question is, will this be fixed?

**Comment by danielga** [comment]
The x86-64 branch is no longer supported.
